# Exercise 1

1. 

In [3]:
import numpy as np

In [8]:
matrix = np.zeros((5, 5))
matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
matrix[:5, :5] = np.arange(3, 8)
matrix

array([[3., 4., 5., 6., 7.],
       [3., 4., 5., 6., 7.],
       [3., 4., 5., 6., 7.],
       [3., 4., 5., 6., 7.],
       [3., 4., 5., 6., 7.]])

2.

In [132]:
matrix = np.arange(16, dtype=int).reshape(4, 4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [136]:
matrix1 = np.hsplit(matrix, 2)
matrix1

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]