# NUMPY - Multidimensional Data Arrays

It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. NumPy brings the computational power of languages like C and Fortran to Python, a language much easier to learn and use.

In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.2'

In [111]:
print(np.info(np.arange))

arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1] - out[i]``

## What is Array?

![](array.png)

In [115]:
# Python List

a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

In [117]:
print(a+b)
print(a*b)

[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: can't multiply sequence by non-int of type 'list'

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



In [118]:
a_array = np.array(a)
b_array = np.array(b)

print(a_array + b_array)
print(a_array * b_array)

[ 6  8 10 12]
[ 5 12 21 32]


## Creating `numpy` arrays

There are some ways to initialize new numpy arrays:
* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### Lists

In [119]:
# vector: the argument to the array function is a list
v = np.array([1, 2, 3, 4, 5])

v

array([1, 2, 3, 4, 5])

In [120]:
# matrix: the argument to the array function is a nested list
m = np.array([[1, 2, 3], [4, 5, 6]])

m

array([[1, 2, 3],
       [4, 5, 6]])

The `v` and `m` objects are both of the type `ndarray` that the `numpy` module provides.

In [121]:
type(v), type(m)

(numpy.ndarray, numpy.ndarray)

In [122]:
a = [1,2,3]

In [123]:
type(a)

list

The difference between the `v` and `m` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [124]:
v.shape

(5,)

In [125]:
m.shape

(2, 3)

The number of elements in the array is available through the `ndarray.size` property

In [126]:
m.size

6

`numpy.ndarray` looks very similiar to the `list`. So, why not use the list instead?
`numpay.ndarray` is used for several reason:
1. Lists are very general. They can contain any kind of object. They do not support mathematical functions such as matrix and dot multiplication, etc. 
2. Numpy arrays are statically typed and homogenous. The type of the elements is determined when the array is created
3. Numpy arrays are memory efficient
4. It is fast for implementation of mathematical function

We can see the type of data of an array using `dtype`

In [127]:
m.dtype

dtype('int32')

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [131]:
m = np.array([[1, 2, 3], [4, 5, 6]], dtype=str)

m
m.dtype

dtype('<U1')

Common data types that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, `object`, etc.

### Create Matrix Zeros

In [132]:
# One dimension

zeros_matrix = np.zeros(5)

zeros_matrix

array([0., 0., 0., 0., 0.])

In [133]:
#two dimension

zeros_matrix2 = np.zeros(5,2)

zeros_matrix2

TypeError: Cannot interpret '2' as a data type

In [134]:
# should  be in tuple format

zeros_matrix2 = np.zeros((5,2)) # 5 rows, 2 columns
zeros_matrix2 

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### Matrix ones

In [135]:
#one dimension

matrix_ones = np.ones(5)
matrix_ones 

array([1., 1., 1., 1., 1.])

In [176]:
#3 dimension

matrix_ones2 = np.ones((3, 4, 2)) #3 rows, 4 columns, 2 depth
matrix_ones2

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

## > Exercise 1

1. Create a matrix from a list which has 4 rows and 3 columns

In [ ]:
my_matrix = np.array([[1,2,3],
                     [2,3,4],
                     [1,2,1],
                     [1,2,2]])
my_matrix

2. Create the following matrix
![](lat11.png)

In [ ]:
my_matrix2 = np.array([[2,7,12,0],
                      [3,9,3,4],
                      [4,0,1,3]])
my_matrix2

3. Create a 2D matrix with size of 10

In [4]:
cara1 = np.array([[1,2,3,4,5],
                 [6,7,8,9,10]])
cara1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
cara2 = np.zeros((2,5))
cara2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
cara3 = np.array([[1,2],
                 [2,2],
                 [2,1],
                 [3,3],
                 [4,5]])
cara3

array([[1, 2],
       [2, 2],
       [2, 1],
       [3, 3],
       [4, 5]])

In [7]:
cara4 = np.array([[1],
                 [2],
                 [2],
                 [3],
                 [4],
                 [9],
                 [10],
                 [10],
                 [7],
                 [1]])
cara4

array([[ 1],
       [ 2],
       [ 2],
       [ 3],
       [ 4],
       [ 9],
       [10],
       [10],
       [ 7],
       [ 1]])

In [8]:
print("Size cara1: ", cara1.size)
print("Size cara2: ", cara2.size)
print("Size cara3: ", cara3.size)
print("Size cara4: ", cara4.size)

Size cara1:  10
Size cara2:  10
Size cara3:  10
Size cara4:  10


In [9]:
print("Shape cara1: ", cara1.shape)
print("Shape cara2: ", cara2.shape)
print("Shape cara3: ", cara3.shape)
print("Shape cara4: ", cara4.shape)

Shape cara1:  (2, 5)
Shape cara2:  (2, 5)
Shape cara3:  (5, 2)
Shape cara4:  (10, 1)


4. Create a 3D matrix of ones which has 2 rows, 3 columns, and 3 depth

In [ ]:
m4 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               
                [[6,2,3],
                [4,5,8],
                [8,8,9]]])

m4

In [ ]:
m4.shape

5. Make the following arrays from zeros arrays and with for loops
![](exercise1.png)

In [10]:
my_array = np.zeros((5,3))
my_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
for i in my_array:
    print(i+2)

[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]


### Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

**arange**

In [137]:
# create a range

x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [139]:
# create a range

x = np.arange(10, 20) # arguments: start, stop

x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [140]:
# create a range

x = np.arange(10, 20, 2) # arguments: start, stop, step

x

array([10, 12, 14, 16, 18])

In [141]:
x = np.arange(-1, 1, 0.1)

x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

The number 9.00000000e-01 already is a floating point number.
It's written in scientific notation and is equivalent to 9 * 10**-1 or 0.9.

#### linspace

In [142]:
# using linspace, both end points ARE included
np.linspace(0, 10, 10) #Unlike arange that uses step, linspace uses the number of sample

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

#### random data

In [ ]:
from numpy import random

In [143]:
#uniform random numbers in [0,1]
random.rand(5,5)

array([[0.11443967, 0.88769762, 0.55200282, 0.42320451, 0.92019945],
       [0.41434104, 0.61865736, 0.18230269, 0.34695794, 0.14238141],
       [0.20921183, 0.38407139, 0.78206701, 0.43332119, 0.11750263],
       [0.2087883 , 0.56530189, 0.87457656, 0.57097814, 0.77944705],
       [0.94689136, 0.94536035, 0.49066854, 0.80642302, 0.16066794]])

In [144]:
# standard normal distributed random numbers
x = random.randn(5,5)
x

array([[ 0.57884305, -0.46492971,  1.27895982, -0.86201059,  0.54383887],
       [-0.66114875, -0.08883153, -0.71689485, -1.94798564,  0.08919842],
       [-1.17792692, -0.61784891, -1.07467415, -0.06259967, -0.31804616],
       [ 0.58895297, -0.52770525,  0.4580862 , -0.05465286, -0.88238409],
       [-1.00103135, -2.13045736, -1.01278058, -0.05389805,  0.0383461 ]])

In [145]:
x.dtype

dtype('float64')

In [ ]:
x = np.ones(2, dtype = np.int64)
x

In [157]:
random.randint(10)

5

In [165]:
random.randint(2, 10, size=4)

array([5, 8, 8, 6])

In [175]:
random.randint(2, 10, size=(4,2,2))

array([[[2, 6],
        [3, 7]],

       [[8, 6],
        [6, 8]],

       [[8, 2],
        [5, 8]],

       [[9, 3],
        [6, 9]]])

## Exercise 2

1. Generate a 1-D array containing 5 random integers from 0 to 100:

In [12]:
random.randint(0,101, size=5)

NameError: name 'random' is not defined

2. Generate a 2-D array with 3 rows, each row contains 5 random integers from 0 to 100

In [ ]:
random.randint(0,101, size=(3,5))

3. Generate a 1-D array of 30 evenly spaced elements between 1.5 and 5.5, inclusive.

In [ ]:
np.linspace(1.5, 5.5, 30)